cmake_minimum_required(VERSION 3.16)
project(CaveConsumers LANGUAGES C CXX)
enable_testing()
find_package(FinalBuildCaves 1 CONFIG REQUIRED)
add_executable(cpp_consumer cpp_consumer.cpp)
target_link_libraries(cpp_consumer PRIVATE fbs::caves)
add_executable(c_consumer c_consumer.c)
target_link_libraries(c_consumer PRIVATE fbs::caves)
add_test(NAME installed_cpp_consumer COMMAND cpp_consumer)
add_test(NAME installed_c_consumer COMMAND c_consumer)
